version: "3.8"

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  postgres_data:
    name: postgres_data_peludosclick

services:
  maintenance_page:
    build: 
      context: ./maintenance
      dockerfile: Dockerfile
    container_name: maintenance-page
    ports:
      - "9002:80"
    labels:
      - traefik.http.routers.maintenance.rule=Host(`www.peludosclick.com`,`peludosclick.com`)
      - traefik.http.routers.maintenance.tls=true
      - traefik.http.routers.maintenance.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: Silvestre1993
      POSTGRES_PASSWORD: iendlshLANDHG423423480
      POSTGRES_DB: peludosclick
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - traefik.enable=true
    networks:
      - internal
      - web
    restart: always

  postgresadmin:
    image: dpage/pgadmin4:4.28
    depends_on: 
       - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: albertdesarrolloweb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Yamaha600
    ports:
      - 5050:5050
    labels:
      - traefik.http.routers.postgresadmin.rule=Host(`pgadmin.peludosclick.com`)
      - traefik.http.routers.postgresadmin.tls=true
      - traefik.http.routers.postgresadmin.tls.certresolver=lets-encrypt
      - traefik.port=5050
    networks:
      - internal
      - web 