version: "3.8"
services:
  parallel_postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: Silvestre1993
      POSTGRES_PASSWORD: iendlshLANDHG423423480
      POSTGRES_DB: peludosclick
    ports:
      -  5432:5432  
  # The Postgres Admin tool if we want to run some custom queries and so on against our Database
  parallel_pgadmin:
    image: dpage/pgadmin4:4.28
    depends_on: 
       - parallel_postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
